/**
 * @file  CorrectionEngine.cpp
 * @brief FIR convolution engine — profile management and processing.
 *
 * FIR data is auto-generated by tools/export_fir.cpp from
 * oratory1990 AutoEQ parametric EQ measurements.
 */

#include "dsp/CorrectionEngine.h"
#include "dsp/fir_data.h"

//==============================================================================
// Known headphone profiles. Keep in sync with export_fir.cpp and
// PluginEditor::profileNames_.
static const HeadphoneProfile profiles[] = {
    { "ATH-M50X",   fir_m50x    },
    { "DT 770 Pro",  fir_dt770   },
    { "HD 600",     fir_hd600   },
    { "DT 990 Pro", fir_dt990pro }
};

//==============================================================================
void CorrectionEngine::prepare (const juce::dsp::ProcessSpec& spec)
{
    currentSpec_ = spec;
    prepared_ = true;
    loadProfile();
}

void CorrectionEngine::reset()
{
    if (prepared_)
        loadProfile();
}

//==============================================================================
void CorrectionEngine::setProfile (int index) noexcept
{
    if (index < 0 || index >= getNumProfiles())
        index = 0;

    currentProfile_ = index;

    // Defer loading until prepare() has been called.
    if (prepared_)
        loadProfile();
}

const char* CorrectionEngine::getProfileName (int index) const noexcept
{
    if (index < 0 || index >= getNumProfiles())
        return "Unknown";

    return profiles[index].name;
}

//==============================================================================
void CorrectionEngine::loadProfile()
{
    jassert (prepared_);
    jassert (currentProfile_ >= 0 && currentProfile_ < getNumProfiles());

    auto& src = profiles[currentProfile_];

    // Copy FIR data into a JUCE array for the convolution API.
    juce::Array<float> ir;
    ir.resize (1024);
    std::copy (src.firData, src.firData + 1024, ir.begin());

    convolution_.loadImpulseResponse (
        static_cast<const void*> (ir.getRawDataPointer()),
        1024 * sizeof (float),
        juce::dsp::Convolution::Stereo::no,      // mono IR, process stereo
        juce::dsp::Convolution::Trim::no,
        currentSpec_.maximumBlockSize,
        juce::dsp::Convolution::Normalise::yes);  // auto-normalise to 0 dB
}

//==============================================================================
void CorrectionEngine::process (juce::AudioBuffer<float>& buffer) noexcept
{
    if (! enabled_)
        return;

    jassert (prepared_); // prepare() must have been called.

    juce::dsp::AudioBlock<float> block (buffer);
    juce::dsp::ProcessContextReplacing<float> context (block);
    convolution_.process (context);
}
